version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lainbot
    restart: unless-stopped
    volumes:
      - ./cache:/app/cache
      - ./env:/app/.env
    environment:
      - NODE_ENV=production